version: "2.0"
services:
  db:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: toor
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
